# ACM20030 - Midterm 2 - 2020

This midterm exam starts at 5pm on Monday 7th of December and lasts **50 minutes** until 5:50pm. Ten additional minutes are given at the end for you to upload the `Midterm2.ipynb` to BrightSpace by 6pm.

Save your notebook regularly as you are solving the problems.

I recommend you have a pen and paper handy to make small calculations (these do not need to be handed in).

The marks for each question are given in square brackets at the start of each question. The total marks for the test is 31.

You must complete the test indivudually. No contact with other class members, or anyone else, is allowed during the test.

When you finish the test you must upload your completed `Midterm2.ipynb` to BrightSpace. You can find the place to upload the file under the Assessments Tab -> Midterm2.

If there are any issues with uploading the midterm to BrightSpace. Please email me your completed Midterm2.ipynb before 6pm. My email address is niels.warburton@ucd.ie. Please include your student number if you email the test to me.

---

If you find it useful to do so you may view the [course examples](https://github.com/nielsw2/ACM20030-Examples) for reference. You may also view the NumPy and Matplotlib documentation if you want.  You should not use the internet to search for solutions. It is usually quite obvious when a student hands in code they have copied from, e.g., StackExchange. Please do not do this. If you hand in an answer that is copied from a webpage you will receive zero marks for that entire question.

You **may not** use any other Python libraries other than NumPy (including linalg) and Matplotlib. 

Please enter your student number in the cell below and run the two cells below that to load the libraries. By entering your student number below you agree to not work with, copy from, or plagarise anyone else during the test.

In [14]:
# Enter student number below
# 19312593

In [15]:
# Import NumPy, linalg and matplotlib
import numpy as np
from numpy import linalg as la
import matplotlib.pyplot as plt

In [16]:
# The below two lines set the default size and font size for matplotlib
plt.rcParams['figure.figsize'] = (16.0, 10.0)
plt.rcParams.update({'font.size': 22})

# Question 1: ordinary differential equations (ODEs)

In the lectures we looked at RK2 and RK4 Runge-Kutta methods for solving ordinary differential equations of the form

$$ y'(x) = f(x,y)$$

Below is the algorithm for an **RK3** method:

\begin{align}
    x_{i+1} &= x_i + \Delta x \\
    k_1 &= f(x_i, y_i) \\
    k_2 &= f\left(x_i + \tfrac{\Delta x}{2}, y_i + \tfrac{\Delta x}{2} k_1 \right) \\
    k_3 &= f\left(x_i + \Delta x, y_i + \Delta x(2k_2 - k_1) \right) \\
    y_{i+1} &= y_i + \tfrac{\Delta x}{6}(k_1 + 4 k_2 + k_3) 
\end{align}

## Q1a [2 marks]

Is this RK3 algorithm an explicit or implicit method? Justify your answer.

In [17]:
# Give you answer below
# The RK3 method is an implicit algotithm because it requires us to compute y_(i+1)

## Q1b [5 marks]

Complete the code below to implement the RK3 method

In [18]:
def RK3(f, dx, x0, y0, imax):
    xi = x0
    yi = y0
    i = 0
    while i < imax:
        k1 = f(xi, yi)
        k2 = f(xi + (dx/2), yi + (dx/2)*k1)
        k3 = f(xi + dx, yi + dx*(2*k2 - k1))
        yi = yi + (dx/6)*(k1 + 4*k2 + k3)
        
        xi += dx
        i  += 1
        
    return [xi, yi]

## Q1c [3 marks]

Test you RK3 function to find the solution, $y(x)$, at $x=1$ for the following ODE

$$y'(x) = -2x - y\quad\text{where}\quad y(0) = -1$$

Use 1000 steps to find the solution.

In [22]:
def dydx(x,y):
    return -2*x - y

RK3(dydx, 0.01, 0, -1, 100)

[1.0000000000000007, -1.1036382771599813]

## Q1d [2 marks]

Find the relative difference between you numerical solution at $x=1$ and the true result given by the analytic solution to the ODE:

$$ y(x) = 2 - 3e^{-x} - 2x$$

In [23]:
result_1 = 2 - 3*np.exp(-1) - 2*(1)
result_2 = RK3(dydx, 0.01, 0, -1, 100) 

diff = result_1 - result_1
print(diff)

0.0


# Question 2 : numerical integration

Use the below `NIntegrate` function to answer the Q2 questions.

In [26]:
def NIntegrate(f, a, b, N, method='Simpsons'):
    dx = (b-a)/N
    xi = a
    i = 0
    area = 0
    while i < N:
        if(method == 'Simpsons'):
            area += dx/6*(f(xi) + 4*f((2*xi+dx)/2) + f(xi+dx))
        elif(method == 'midpoint'):
            area += dx * f(xi+dx/2)
        elif(method == 'trapezoidal'):
            area += dx/2 * (f(xi) + f(xi+dx))
        xi += dx
        i+= 1
    return area

## Q2a [3 marks]

Numerically evaluate the following integral using the **midpoint** method with 1000 strips

$$\int_0^{\pi/2} \sin(2x)\,dx $$

Also compute the relative error with respect to the true answer

In [29]:
def g(x):
    np.sin(2*x)
    
NIntegrate(g, 0, np.pi/2, 1000, 'midpoint')

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

## Q2b [4 marks]

There is another (less efficient) form of Simpson's method known as the Simpson's 3/8ths rule. This rule gives the area for each strip as:

$$ I_i = \frac{\Delta x}{8} \left( f(x_i) + 3f\left(x_i + \tfrac{\Delta x}{3}\right) + 3f\left(x_i + \tfrac{2\Delta x}{3}\right) + f(x_i + \Delta x)  \right) $$

Modify the `NIntegrate` function above to implement the Simpson's 3/8ths rule as a new optional method.

## Q2c [2 marks]

Test your new method by evaluating the integral given in Q2a with 1000 strips. Compute the relative error with respect to the true answer. If your answer to part Q2b is correct you should find that your approximation to the integral is much more accurate than the result in Q2a computed using the midpoint method.

In [43]:
def NIntegrate(f, a, b, N, method='Simpsons'):
    dx = (b-a)/N
    xi = a
    i = 0
    area = 0
    while i < N:
        if(method == 'Simpsons'):
            area += dx/6*(f(xi) + 4*f((2*xi+dx)/2) + f(xi+dx))
        elif(method == 'Simpsons3/8'):
            area += (dx/8)*(f(xi) + 3*f(xi+(dx/3)) + f(xi+dx)
        elif(method == 'midpoint'):
            area += dx * f(xi+dx/2)
        elif(method == 'trapezoidal'):
            area += dx/2 * (f(xi) + f(xi+dx))
        xi += dx
        i+= 1
    return area
                            
NIntegrate(g, 0, np.pi/2, 1000, 'Simpsons3/8')

SyntaxError: invalid syntax (<ipython-input-43-6ab3f65c6c17>, line 11)

## Q2d [4 marks]

Let $h(x)$ be the following continous (but not smooth) function

$$ h(x) = \begin{cases} 
      \sin(x) & x \leq 0 \\
      -x^2 & 0\leq x \leq 1 \\
      -\cos(x-1) & x \geq 1 
   \end{cases} $$
   
Define a single function for $h(x)$ which may use `if`, `elif` and `else`. Then use the `NIntegrate` function to evaluate the following integral

$$ \int_{-1}^2 h(x)\, dx $$

using 3000 strips.

Hint: for full marks perform the integration over three seperate regions and use 1000 strips per region.

In [73]:
def h(x):
    if x <= 0:
        return np.sin(x)
    elif 0 <= x <= 1:
        return -x**2
    elif x >= 1:
        return -np.cos(x-1)

I1 = NIntegrate(h, -1, 0, 1000)
I2 = NIntegrate(h, 0, 1, 1000)
I3 = NIntegrate(h, 1, 2, 1000)

answer = I1 + I2 + I3

print(answer)
    


-1.6345020122731246


# Q3 eigensystems

## Q3a [2 marks]

Without computing the inverse or determinant of the matrix $M$ check if numerically inverting $M$ will lead to large numerical errors. You can use any function from `linalg` to make the check. Justify your answer

In [36]:
M = np.array([
    [0.755378492705379, 0.6134083399272159, 0.581809153982142],
    [2.0255256015498575, 0.78939010095135, 0.7399156829587783],
    [0.8467647392295856, 0.11732117401602271, 0.10540435265102421]])

In [45]:
eigensystem = la.eig(M)
la.cond(M)

# condition number is very large which indicates that there will be large numerical error

1551028276162954.2

## Q3b [4 marks]

Let $\lambda_i$ be the eigenvalues of the matrix $B$ and $e_i$ be the eigenvectors of $B$.

For the matrix $B$ given below show that $P^{-1} B P = D$ where $D = \text{diag}(\lambda_1, \lambda_2, \lambda_3)$ and $P$ is a matrix whose **columns** are the eigenvectors of B. 

A good way to answer this question is to show that $P^{-1} B P - D = 0$ (to within machine precision).

Reminder: the `la.eig()` function returns the eigenvalues and eigenvectors, and the eigenvectors are stored as the columns of a matrix.

Hint: you might find `np.identity(n)` useful for constructing an $n\times n$ identity matrix

In [47]:
B = np.array([[1.7, 2.5, 2.4], [5.5, 1.2, 8.8], [6.1, 4.7, 2.4]])

In [79]:
eigensystem = la.eig(B)

P = eigensystem[1]
inv_P = la.inv(P)

def column(matrix, i):
    return [row[i] for row in matrix]

eigenvalues = column(eigensystem, 0)
iden = np.identity(3)
D_matrix = eigensystem[0]*iden
diagonalising_matrix = inv_P@B@P
print(diagonalising_matrix - D_matrix)

[[-1.77635684e-15  3.10862447e-15 -1.77635684e-15]
 [ 4.44089210e-15 -2.44249065e-15  8.32667268e-16]
 [ 4.44089210e-15 -1.44328993e-15  8.88178420e-16]]


# Submission

You must upload your completed `Midterm2.ipynb` to BrightSpace. You can find the place to upload the file under the Assessments Tab -> Midterm2.

If there are any issues with uploading the midterm to BrightSpace. Please email me your completed Midterm2.ipynb. My email address is niels.warburton@ucd.ie.