#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [1]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [2]:
A = np.array([[1,2], [3,4]])
shape = A.shape
R = shape[0]
t_matrix = []

def column(matrix, i):
    return [row[i] for row in matrix]

def flattened_elements(A):
    print(A)
    all_matrix_elements = []
    for row in A:
        for element in row:
            all_matrix_elements.append(element)
    return all_matrix_elements

def transposefunction(A, R):
    for i in range(0,R):
        row_new = column(A, i)
        t_matrix.append(row_new)
    return t_matrix

def check_symmetry(A, B):
    A_shape = A.shape
    if A_shape[0] != A_shape[1]:
        return False

def check_symmetric(A):
    return all(flattened_elements(A == transposefunction(A, A.shape[0])))

#final attempt: 

def is_symmetric(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if matrix[i][j] != matrix[j][i]:
                return False
    return True

Test your function on the two matrices below

In [3]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [4]:
is_symmetric(A)
is_symmetric(SymMatrix)

True

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [5]:
def transposefunction(A):
    t_matrix = []
    R = A.shape[0]
    for i in range(0,R):
        row_new = column(A, i)
        t_matrix.append(row_new)
    return np.array(t_matrix)

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [6]:
A = np.random.rand(6,6);
print(A, transposefunction(A))

transposefunction(A) == A 
transposefunction(transposefunction(A)) - A == 0

[[0.13364438 0.85439359 0.43430576 0.42856668 0.0724342  0.13428854]
 [0.2686278  0.06380617 0.75261928 0.38696334 0.18845875 0.92440046]
 [0.01961581 0.22532679 0.03464556 0.05379165 0.58019023 0.76755151]
 [0.32614296 0.11020762 0.48062627 0.90168251 0.08754259 0.57072889]
 [0.78417912 0.97093079 0.72391008 0.39056465 0.67658947 0.1606641 ]
 [0.54093582 0.48331658 0.16009933 0.88880709 0.95286354 0.2884447 ]] [[0.13364438 0.2686278  0.01961581 0.32614296 0.78417912 0.54093582]
 [0.85439359 0.06380617 0.22532679 0.11020762 0.97093079 0.48331658]
 [0.43430576 0.75261928 0.03464556 0.48062627 0.72391008 0.16009933]
 [0.42856668 0.38696334 0.05379165 0.90168251 0.39056465 0.88880709]
 [0.0724342  0.18845875 0.58019023 0.08754259 0.67658947 0.95286354]
 [0.13428854 0.92440046 0.76755151 0.57072889 0.1606641  0.2884447 ]]


array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [7]:
def flattened_elements(A):
    all_matrix_elements = []
    for row in A:
        for element in row:
            all_matrix_elements.append(element)
    return all_matrix_elements
          
def max_element_list(A):
    len_list = len(A)
    current_biggest = 0 
    for i in range(0, len_list):
        if A[i] > current_biggest:
            current_biggest = A[i]
    return current_biggest

def max_entry(matrix):
    list_flattened_elements = flattened_elements(matrix)
    max_entry = max_element_list(list_flattened_elements)
    return max_entry

Check your result by comparing to `np.max(A)` for the below random matrix

In [8]:
A = np.random.rand(4,5)

result_1 = np.max(A)
result_2 = max_entry(A)

print(flattened_elements(A))

print(A)
print(result_1)
print(result_2)

if result_1 == result_2:
    print("function works")
else:
    print("function does not work")

[0.5681929855880562, 0.6463964949265748, 0.21301389920405378, 0.8435665169535759, 0.4229346956127523, 0.3257585823230461, 0.9627696928250067, 0.9582830951989048, 0.1632621029397816, 0.7360627888005938, 0.3216900148946107, 0.6575392804200131, 0.36772368080358486, 0.32504269864818935, 0.6197182224390392, 0.8504954939160676, 0.11968100059923514, 0.3104236273040025, 0.49618888598820865, 0.29646607912915945]
[[0.56819299 0.64639649 0.2130139  0.84356652 0.4229347 ]
 [0.32575858 0.96276969 0.9582831  0.1632621  0.73606279]
 [0.32169001 0.65753928 0.36772368 0.3250427  0.61971822]
 [0.85049549 0.119681   0.31042363 0.49618889 0.29646608]]
0.9627696928250067
0.9627696928250067
function works


Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

In [9]:
def one_norm(A):
    norm = []
    A_shape = A.shape
    R = A_shape[1]
    for i in range(0, R):
        column_a = column(A, i)
        sum_column = sum(np.abs(column_a))
        norm.append(sum_column)
        norm_max = max(norm)
    return norm_max   

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [10]:
A = np.random.rand(3,4)

result_1 = one_norm(A)
result_2 = la.norm(A, 1)

if result_1 == result_2:
    print("function works")
else:
    print("function does not work")

function works


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [11]:
def infinity_norm(A):
    norm = []
    A_shape = A.shape
    R = A_shape[0]
    for i in range(0, R):
        row_a = A[i]
        sum_row = sum(np.abs(row_a))
        norm.append(sum_row)
        norm_max = max(norm)
    return norm_max  

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [12]:
A = np.random.rand(3,4)

result_1 = infinity_norm(A)
result_2 = la.norm(A, np.inf)

if result_1 == result_2:
    print("function works")
else:
    print("function does not work")

function works


Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [13]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [14]:
cond_num1 = la.cond(A1, 2)
cond_num2 = la.cond(A2, 2)
cond_num3 = la.cond(A3, 2)

print("""When a condition number is very large, the matrix is said to be ill-conditioned, 
here we can clearly see that the condition number of A1 is very large""")

When a condition number is very large, the matrix is said to be ill-conditioned, 
here we can clearly see that the condition number of A1 is very large


# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

In [15]:
b = np.array([[1, 2, 3, 4]])
b_add_db = np.array([[1.1, 2, 3, 4]])
db = np.array([[0.1, 0, 0, 0]])

#Ax = b

def inverse_difference(A, b):
    x1 = b@la.inv(A)
    x1_added = (b_add_db)@la.inv(A)
    dx = x1_added - x1
    return np.array(column(dx, 0))

inverse_diff_x1 = inverse_difference(A1, b)
inverse_diff_x2 = inverse_difference(A2, b)

x1 = b@la.inv(A1)
x2 = b@la.inv(A2)

norm_inverse_diff_x1 = la.norm(inverse_diff_x1, 2)
norm_inverse_diff_x2 = la.norm(inverse_diff_x2, 2)
norm_x1 = la.norm(x1, 2)
norm_x2 = la.norm(x2, 2)
norm_b = la.norm(b, 2)
norm_db = la.norm(db, 2)

percentage_change_A1 = (norm_inverse_diff_x1/norm_x1)*100
percentage_change_A2 = (norm_inverse_diff_x2/norm_x2)*100
precentage_change_db = (norm_db/norm_b)*100

print(percentage_change_A1)
print(percentage_change_A2)
print(precentage_change_db)

6.146504725450837
1.7996031019808383
1.8257418583505536


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [16]:
# Answer here
"""We have clearly shown here that A1 is an ill conditioned matrix as a small change in b (1.826%) gives rise to
a large change in A1 (7.275%). Additionally A2 is not an ill conditioned matrix as the change in b gives rise to 
a small change in A2 (1.266%)

This was guessed in question 3a using condtional numbers"""

'We have clearly shown here that A1 is an ill conditioned matrix as a small change in b (1.826%) gives rise to\na large change in A1 (7.275%). Additionally A2 is not an ill conditioned matrix as the change in b gives rise to \na small change in A2 (1.266%)\n\nThis was guessed in question 3a using condtional numbers'

Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [52]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [62]:
values = la.eig(A)

values_list = list(values[0])
sorted_eigenvalues = np.sort(values_list)[::-1]

# zip() takes 2 lists, the first element of the first list and the first element of second list and puts them in a tuple

for eigenvalue, eigenvector in zip(values[0], np.transpose(np.array(values[1]))):
    print(A@eigenvector, eigenvalue*eigenvector)

[ -6.1962015   -7.01266016 -12.71289871] [ -6.1962015   -7.01266016 -12.71289871]
[ 1.83806756 -0.74382849 -0.52676368] [ 1.83806756 -0.74382849 -0.52676368]
[ 0.12430099 -0.98053324  0.79103825] [ 0.12430099 -0.98053324  0.79103825]


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [19]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

In [20]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    
    # Create a random initial vector
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        Ax      = A@x
        lamprev = lam
        lam = la.norm(Ax,2)/la.norm(x,2)
        x = Ax
        
    x = x/la.norm(x)
    return (lam,x)

Check your answers against Numpy's results from `la.eig(A)`

Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.