#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [17]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [18]:
A = np.array([[1,2], [3,4]])
shape = A.shape
R = shape[0]
t_matrix = []

def column(matrix, i):
    return [row[i] for row in matrix]

def flattened_elements(A):
    print(A)
    all_matrix_elements = []
    for row in A:
        for element in row:
            all_matrix_elements.append(element)
    return all_matrix_elements

def transposefunction(A, R):
    for i in range(0,R):
        row_new = column(A, i)
        t_matrix.append(row_new)
    return t_matrix

def check_symmetry(A, B):
    A_shape = A.shape
    if A_shape[0] != A_shape[1]:
        return False

def check_symmetric(A):
    return all(flattened_elements(A == transposefunction(A, A.shape[0])))

#final attempt: 

def is_symmetric(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if matrix[i][j] != matrix[j][i]:
                return False
    return True

Test your function on the two matrices below

In [19]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [20]:
is_symmetric(A)
is_symmetric(SymMatrix)

True

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [21]:
def transposefunction(A):
    t_matrix = []
    R = A.shape[0]
    for i in range(0,R):
        row_new = column(A, i)
        t_matrix.append(row_new)
    return np.array(t_matrix)

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [22]:
A = np.random.rand(6,6);
print(A, transposefunction(A))

transposefunction(A) == A 
transposefunction(transposefunction(A)) - A == 0

[[0.89855561 0.15045162 0.69487261 0.0286363  0.93672123 0.1034766 ]
 [0.07469017 0.22303338 0.28459266 0.75058148 0.73375242 0.01978231]
 [0.61230582 0.45618193 0.8039047  0.46358233 0.81059873 0.32493954]
 [0.45800459 0.40029587 0.46258186 0.21707223 0.9872304  0.09047492]
 [0.73739069 0.42672077 0.34238985 0.89933414 0.78102541 0.38366366]
 [0.07424922 0.49326903 0.77317676 0.39728953 0.70254761 0.07480229]] [[0.89855561 0.07469017 0.61230582 0.45800459 0.73739069 0.07424922]
 [0.15045162 0.22303338 0.45618193 0.40029587 0.42672077 0.49326903]
 [0.69487261 0.28459266 0.8039047  0.46258186 0.34238985 0.77317676]
 [0.0286363  0.75058148 0.46358233 0.21707223 0.89933414 0.39728953]
 [0.93672123 0.73375242 0.81059873 0.9872304  0.78102541 0.70254761]
 [0.1034766  0.01978231 0.32493954 0.09047492 0.38366366 0.07480229]]


array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [23]:
def flattened_elements(A):
    all_matrix_elements = []
    for row in A:
        for element in row:
            all_matrix_elements.append(element)
    return all_matrix_elements
          
def max_element_list(A):
    len_list = len(A)
    current_biggest = 0 
    for i in range(0, len_list):
        if A[i] > current_biggest:
            current_biggest = A[i]
    return current_biggest

def max_entry(matrix):
    list_flattened_elements = flattened_elements(matrix)
    max_entry = max_element_list(list_flattened_elements)
    return max_entry

Check your result by comparing to `np.max(A)` for the below random matrix

In [24]:
A = np.random.rand(4,5)

result_1 = np.max(A)
result_2 = max_entry(A)

print(flattened_elements(A))

print(A)
print(result_1)
print(result_2)

if result_1 == result_2:
    print("function works")
else:
    print("function does not work")

[0.38831370844620794, 0.905718582968413, 0.5945418308040735, 0.22801306503332408, 0.7630564216577331, 0.4039037576478156, 0.06094358842905201, 0.21746098738654518, 0.8322325766129491, 0.43057028477217174, 0.5297685917862052, 0.9674183102412446, 0.748623585484207, 0.8637754275455006, 0.46262237329880573, 0.16058132164304129, 0.8509687118630379, 0.8355391191124193, 0.18501197807631986, 0.9432591900400769]
[[0.38831371 0.90571858 0.59454183 0.22801307 0.76305642]
 [0.40390376 0.06094359 0.21746099 0.83223258 0.43057028]
 [0.52976859 0.96741831 0.74862359 0.86377543 0.46262237]
 [0.16058132 0.85096871 0.83553912 0.18501198 0.94325919]]
0.9674183102412446
0.9674183102412446
function works


Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

In [25]:
def one_norm(A):
    norm = []
    A_shape = A.shape
    R = A_shape[1]
    for i in range(0, R):
        column_a = column(A, i)
        sum_column = sum(np.abs(column_a))
        norm.append(sum_column)
        norm_max = max(norm)
    return norm_max   

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [26]:
A = np.random.rand(3,4)

result_1 = one_norm(A)
result_2 = la.norm(A, 1)

if result_1 == result_2:
    print("function works")
else:
    print("function does not work")

function works


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [27]:
def infinity_norm(A):
    norm = []
    A_shape = A.shape
    R = A_shape[0]
    for i in range(0, R):
        row_a = A[i]
        sum_row = sum(np.abs(row_a))
        norm.append(sum_row)
        norm_max = max(norm)
    return norm_max  

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [28]:
A = np.random.rand(3,4)

result_1 = infinity_norm(A)
result_2 = la.norm(A, np.inf)

if result_1 == result_2:
    print("function works")
else:
    print("function does not work")

function works


Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [29]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [30]:
cond_num1 = la.cond(A1, 2)
cond_num2 = la.cond(A2, 2)
cond_num3 = la.cond(A3, 2)

print("""When a condition number is very large, the matrix is said to be ill-conditioned, 
here we can clearly see that the condition number of A1 is very large""")

When a condition number is very large, the matrix is said to be ill-conditioned, 
here we can clearly see that the condition number of A1 is very large


# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

In [38]:
b = np.array([[1, 2, 3, 4]])
b_add_db = np.array([[1.1, 2, 3, 4]])
db = np.array([[0.1, 0, 0, 0]])

#Ax = b

def inverse_difference(A, b):
    x1 = b@la.inv(A)
    x1_added = (b_add_db)@la.inv(A)
    dx = x1_added - x1
    return np.array(column(dx, 0))

inverse_diff_x1 = inverse_difference(A1, b)
inverse_diff_x2 = inverse_difference(A2, b)

x1 = b@la.inv(A1)
x2 = b@la.inv(A2)

norm_inverse_diff_x1 = la.norm(inverse_diff_x1, 2)
norm_inverse_diff_x2 = la.norm(inverse_diff_x2, 2)
norm_x1 = la.norm(x1, 2)
norm_x2 = la.norm(x2, 2)
norm_b = la.norm(b, 2)
norm_db = la.norm(db, 2)

percentage_change_A1 = (norm_inverse_diff_x1/norm_x1)*100
percentage_change_A2 = (norm_inverse_diff_x2/norm_x2)*100
precentage_change_db = (norm_db/norm_b)*100

print(percentage_change_A1)
print(percentage_change_A2)
print(precentage_change_db)

6.146504725450837
1.7996031019808383
1.8257418583505536


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [32]:
# Answer here
"""We have clearly shown here that A1 is an ill conditioned matrix as a small change in b (1.826%) gives rise to
a large change in A1 (7.275%). Additionally A2 is not an ill conditioned matrix as the change in b gives rise to 
a small change in A2 (1.266%)

This was guessed in question 3a using condtional numbers"""

'We have clearly shown here that A1 is an ill conditioned matrix as a small change in b (1.826%) gives rise to\na large change in A1 (7.275%). Additionally A2 is not an ill conditioned matrix as the change in b gives rise to \na small change in A2 (1.266%)\n\nThis was guessed in question 3a using condtional numbers'

Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [33]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [34]:
values = la.eig(A)

values_list = list(values[0])
sorted_eigenvalues = np.sort(values_list)[::-1]
print(sorted_eigenvalues)



#print(values)

# print(A*values[1][0])
# print(values[0][0]*values[1][0])

[15.78569318  1.26595327 -2.05164645]


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [35]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

In [19]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    
    # Create a random initial vector
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        Ax      = A@x
        lamprev = lam
        lam = la.norm(Ax,2)/la.norm(x,2)
        x = Ax
        
    x = x/la.norm(x)
    return (lam,x)

Check your answers against Numpy's results from `la.eig(A)`

Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.